### PR TITLE
nonblocking check of pollables when reactor is busy

### LINKED ISSUE #73: Futures should be woken before calling Future::poll
## Problem

Following up on https://github.com/yoshuawuyts/wstd/pull/71, we still have some issues. In https://github.com/yoshuawuyts/wstd/pull/70#issuecomment-30509222320 @SilverMira provided the following failing test case:

```rust
    #[test]
    fn cooperative_concurrency() {
        crate::runtime::block_on(async {
            let cpu_heavy = async move {
                // Simulating a CPU-heavy task that runs for 10 second and yields occasionally
                for _ in 0..100 {
                    std::thread::sleep(std::time::Duration::from_millis(100));
                    futures_lite::future::yield_now().await;
                }
                true
            };
            let timeout = async move {
                crate::time::Timer::after(crate::time::Duration::from_secs(3))
                    .wait()
                    .await;
                false
            };
            let mut future_group = futures_concurrency::future::FutureGroup::<
                Pin<Box<dyn std::future::Future<Output = bool>>>,
            >::new();
            future_group.insert(Box::pin(cpu_heavy));
            future_group.insert(Box::pin(timeout));
            let result = future_group.next().await;
            assert_eq!(result, Some(false), "cpu_heavy task should have timed out");
        });
    }
```

From talking with @pchickey, it sounds like we are currently not calling the wakers before re-polling, which is causing the test to fail. We should write a patch to fix that.

## Proposed Solution

The solution @pchickey is proposing is to add a non-blocking version of [`Reactor::block_on_pollables`](https://github.com/yoshuawuyts/wstd/blob/90bb588c4f10030e2ac6fcdb13860d7da1a62b8d/src/runtime/reactor.rs#L130) which calls `wasi::io::poll::poll` on every async pollable with a waker registered. We need a variation in the behavior that adds an additional pollable to the wasi poll list, so that `wasi::io::poll::poll` does not block and immediately returns a ready list, and wakes all of the associated wakers. We should insert that call right below the following line:

https://github.com/yoshuawuyts/wstd/blob/90bb588c4f10030e2ac6fcdb13860d7da1a62b8d/src/runtime/block_on.rs#L40

### PR DESCRIPTION
**Pull request by pchickey**
Fixes #73.

Add test provided by @SilverMira in #70, tracked in #73.

Add a `nonblock_check_pollables` function to the reactor, for use in the "busy case" of the block_on loop. Factor out `check_pollables`, the common part of `block_on_pollables` and `nonblock_check_pollables`.

### CODE REVIEW

File: src/runtime/reactor.rs [hunk 1]
```diff
@@ -321,4 +365,31 @@ mod test {
...
+                    .wait()
+                    .await;
+                false
+            };
+            let mut future_group = futures_concurrency::future::FutureGroup::<
+                Pin<Box<dyn std::future::Future<Output = bool>>>,
+            >::new();
+            future_group.insert(Box::pin(cpu_heavy));
+            future_group.insert(Box::pin(timeout));
+            let result = futures_lite::StreamExt::next(&mut future_group).await;
```
Comment (yoshuawuyts) [inline src/runtime/reactor.rs:391]: I'm surprised this doesn't work here? Afaict this is just `race`-semantics?


```suggestion
            let result = (cpu_heavy, timeout).race().await;
```

Assuming `futures_concurrency::prelude::*;` is imported of course.

File: src/runtime/reactor.rs [hunk 2]
```diff
@@ -128,8 +128,58 @@ impl Reactor {
...
+        })
+    }
+
+    /// Without blocking, check for any ready pollables and wake the
+    /// associated futures.
+    pub(crate) fn nonblock_check_pollables(&self) {
+        // Lazily create a pollable which always resolves to ready.
+        use std::sync::LazyLock;
+        static READY_POLLABLE: LazyLock<Pollable> =
+            LazyLock::new(|| wasi::clocks::monotonic_clock::subscribe_duration(0));
```
Comment (yoshuawuyts) [inline src/runtime/reactor.rs:148]: Ha, it feels like we're almost missing a built-in for this in the component model?

cc/ @lukewagner check this out

File: src/runtime/reactor.rs [hunk 3]
```diff
@@ -128,8 +128,58 @@ impl Reactor {
...
+    where
+        F: FnOnce(&[&Pollable]) -> Vec<u32>,
+    {
         let reactor = self.inner.borrow();
 
+        // If no wakers are pending on pollables, there is no work to be done
+        // here:
+        if reactor.wakers.is_empty() {
+            return;
+        }
```
Comment (yoshuawuyts) [inline src/runtime/reactor.rs:181]: This one caught me off guard a little. I assume it's correct, but I'm not sure *why* it's correct. Can you elaborate a little more in the comment?

On line 135 we panic if the list of pollables is empty, but apparently having an empty list of wakers is not a problem. Saying a little more about that would be helpful to me at least.

File: src/runtime/reactor.rs (hunk 2 above)
Comment (pchickey) [reply src/runtime/reactor.rs:148]: My understanding is that there is a non-blocking mechanism to check if a waitable set contains any ready waitables in p3, so this wont be an issue there.

File: src/runtime/reactor.rs (hunk 3 above)
Comment (pchickey) [reply src/runtime/reactor.rs]: This is a good catch, this would have subtly introduced bad behavior in the blocking case, so I added a commit that changes how this is implemented. In the nonblocking case (i.e. the root future is pending but has been woken), we want to skip these calculations and poll call if it cannot wake any other futures. In the blocking case, we want to panic with the most informative message possible, rather than rely on a debug assert, or let wasi trap and the user have to work out why.

File: src/runtime/reactor.rs (hunk 2 above)
Comment (lukewagner) [reply src/runtime/reactor.rs:161]: Yep, that's right @pchickey: calling `waitable-set.poll` or returning the `POLL` code from a `callback` is non-blocking.
